# traefik/config.yml
http:
  routers:
    traefik:
      rule: "Host(`traefik.local`)"
      service: "api@internal"
      tls:
        domains:
          - main: "local"
            sans:
              - "*.local"
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
