api:
  dashboard: true
  insecure: true
  debug: true

providers:
  docker:
    swarmMode: false
    exposedByDefault: true
    watch: true
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: DEBUG
  format: common

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
